pipeline {
    agent any
    stages {

        stage("build"){
            steps{
                echo 'buid the code...'
                nodejs('nodejs15'){
                    sh 'npm install'
                }
            }
        }

        stage('docker-package') {
            agent any
            when {
                branch 'master'
            }
            steps {
                echo 'Packaging app with docker'
                script {
                    docker.withRegistry('https://index.docker.io/v1/','dennis-dockerhub-login') {
                        def appImage = docker.build("56373480/practica3-app:master", "./tallerApp/")
                        appImage.push('master')
                    }
                }

            }
        }

        stage("Deploy dev"){
            when {
                branch 'master'
            }
            steps{
                echo 'deploy the code in development environment'
                script {
                    withCredentials([usernamePassword(credentialsId: 'chef-dev-node', usernameVariable: 'USERNAME', passwordVariable: 'PASSWORD')]) {
                        def remote = [:]
                        remote.name = 'chef-dev'
                        remote.host = '64.225.58.243'
                        remote.allowAnyHosts = true
                        remote.user = USERNAME
                        remote.password = PASSWORD
                        sshCommand remote: remote, command: 'chef-client'
                    }
                }
            }
        }

        stage("Deploy production"){
            when {
                branch 'master'
            }
            steps{
                echo 'deploy the code in production environment'
                script {
                    withCredentials([usernamePassword(credentialsId: 'chef-prod-node', usernameVariable: 'USERNAME', passwordVariable: 'PASSWORD')]) {
                        def remote = [:]
                        remote.name = 'aws'
                        remote.host = '104.236.30.46'
                        remote.allowAnyHosts = true
                        remote.user = USERNAME
                        remote.password = PASSWORD
                        sshCommand remote: remote, command: 'chef-client'
                    }
                }
            }
        }
    }
}